# Generated by Django 3.2.5 on 2021-07-27 16:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2021, 7, 27, 16, 2, 4, 222715, tzinfo=utc))),
                ('court', models.FloatField(default=0)),
                ('personal', models.FloatField(default=0)),
                ('training', models.FloatField(default=0)),
                ('equipment', models.FloatField(default=0)),
                ('meetings', models.FloatField(default=0)),
                ('accident', models.FloatField(default=0)),
                ('crime', models.FloatField(default=0)),
                ('patrol_coverage', models.FloatField(default=0)),
                ('call_out', models.FloatField(default=0)),
                ('other', models.FloatField(default=0)),
                ('enforcement_stops', models.IntegerField(default=0)),
                ('citations', models.IntegerField(default=0)),
                ('mechanicals', models.IntegerField(default=0)),
                ('OTS_Cites', models.IntegerField(default=0)),
                ('complaint_areas', models.IntegerField(default=0)),
                ('accident_reports', models.IntegerField(default=0)),
                ('accident_sups', models.IntegerField(default=0)),
                ('arrests', models.IntegerField(default=0)),
                ('NAT', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
